Traceback (most recent call last):
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/emily/anaconda3/envs/MACS497/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pooch
url = "https://www.ldeo.columbia.edu/~rpa/float_data_4901412.zip"
files = pooch.retrieve(url, processor=pooch.Unzip(), known_hash="2a703c720302c682f1662181d329c9f22f9f10e1539dc2d6082160a469165009")
files
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpooch[39;00m
[1;32m      2[0m url [38;5;241m=[39m [38;5;124m"[39m[38;5;124mhttps://www.ldeo.columbia.edu/~rpa/float_data_4901412.zip[39m[38;5;124m"[39m
[1;32m      3[0m files [38;5;241m=[39m pooch[38;5;241m.[39mretrieve(url, processor[38;5;241m=[39mpooch[38;5;241m.[39mUnzip(), known_hash[38;5;241m=[39m[38;5;124m"[39m[38;5;124m2a703c720302c682f1662181d329c9f22f9f10e1539dc2d6082160a469165009[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'pooch'
ModuleNotFoundError: No module named 'pooch'

